local ok, err = pcall(function()
  local settings = require("config.settings")
  assert(settings.resolve().features.input)
  assert(not settings.resolve({ features = { input = false } }).features.input)
  assert(not settings.resolve({ features = { input = true } }, "core").features.input)
  assert(not pcall(settings.resolve, {}, "unknown"))
  assert(not pcall(settings.resolve, { features = { unknown = true } }))
  assert(not pcall(settings.resolve, { features = { input = "yes" } }))
  assert(not pcall(settings.resolve, false))
  assert(settings.resolve().features.lsp and settings.resolve().languages.lua)
  assert(not settings.resolve({ features = { lsp = false } }).features.lsp)
  assert(not settings.resolve({}, "core").features.lsp)
  assert(not settings.resolve({ languages = { lua = false } }).languages.lua)
  assert(not pcall(settings.resolve, { languages = { unknown = true } }))
  assert(not pcall(settings.resolve, { languages = { lua = "yes" } }))
  assert(settings.resolve().features.picker)
  assert(not settings.resolve({ features = { picker = false } }).features.picker)
  assert(not settings.resolve({}, "core").features.picker)
  assert(not pcall(settings.resolve, { features = { picker = "yes" } }))
  assert(settings.resolve().features.theme)
  assert(not settings.resolve({ features = { theme = false } }).features.theme)
  assert(not settings.resolve({ features = { theme = true } }, "core").features.theme)
  assert(not pcall(settings.resolve, { features = { theme = "yes" } }))
  assert(settings.resolve().features.treesitter)
  assert(not settings.resolve({ features = { treesitter = false } }).features.treesitter)
  assert(not settings.resolve({ features = { treesitter = true } }, "core").features.treesitter)
  assert(not pcall(settings.resolve, { features = { treesitter = "yes" } }))
  assert(settings.resolve().features.textobjects)
  assert(not settings.resolve({ features = { textobjects = false } }).features.textobjects)
  assert(not settings.resolve({ features = { textobjects = true } }, "core").features.textobjects)
  assert(not pcall(settings.resolve, { features = { textobjects = "yes" } }))
  assert(settings.resolve().features.git)
  assert(not settings.resolve({ features = { git = false } }).features.git)
  assert(not settings.resolve({ features = { git = true } }, "core").features.git)
  assert(not pcall(settings.resolve, { features = { git = "yes" } }))
  io.stdout:write("Settings checks: 33 passed\n")
  io.stdout:flush()
end)
if not ok then
  io.stderr:write(tostring(err) .. "\n")
  vim.cmd.cquit(1)
end
vim.cmd.qa({ bang = true })
